name: ci
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  test:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/build
      - name: Install packages
        run: flutter pub get
      - name: Code gen l10n
        run: flutter gen-l10n  --no-nullable-getter
      - name: Format
        run: dart format $(find lib -name "*.dart" -not \( -name "*.*freezed.dart" -o -name "*.*g.dart" -o -name "oss_licenses.dart" \) ) --set-exit-if-changed
      - name: Linter
        run: flutter analyze --no-fatal-infos