name: ci
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  test:
    name: flutter lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: stable
          flutter-version: ${{ steps.asdf.outputs.flutter }}
          cache: true
      - name: Install packages
        run: flutter pub get
      - name: Format
        run: dart format $(find lib -name "*.dart" -not \( -name "*.*freezed.dart" -o -name "*.*g.dart" -o -name "oss_licenses.dart" \) ) --set-exit-if-changed
      - name: Linter
        run: flutter analyze --no-fatal-infos